### ISSUE TITLE
dependencia de acpi

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/huayra-recovery#6]
Agregar dependecia del comando acpi al paquete (se usa para obtener el estado del adaptador de corriente)

**Comment by matiasdelellis** [comment]
Eh vo.. Hace 4 añor reportaste esto.. jaaj

**Comment by ftoledo** [comment]
si hay que agregar asi te lo instala ya que lo usa para saber si esta conectado el cargador

**Comment by matiasdelellis** [comment]
Arreglado en single-branch pero no en master que tiene ambos sistemas.. Lo dejo abierto..
